version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/home/work/notebook"
      - ".jupyter:/root/.jupyter"
    ports:
      - "8888:8888"
    tty: true
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''

# https://www.idnet.co.jp/column/page_187.html
# https://qiita.com/ao_log/items/5438f2aaf5c2b46d2ccb