version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile-jupyter
    container_name: jupyter
    volumes:
      - ".:/home/work/notebook"
      - ".jupyter:/root/.jupyter"
    ports:
      - "8888:8888"
    tty: true
    environment:
      - JUPYTER_ENABLE_LAB=yes
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
  selenium:
    build:
      context: .
      dockerfile: Dockerfile-selenium
    container_name: selenium_chrome
    image: selenium_chrome
    volumes:
      - ".:/home/work/notebook"
      - ".jupyter:/root/.jupyter"
    ports: # noNVC connection
      - "7979:7900"
      - "4444:4444"
    shm_size: 2gb
    tty: true

# https://www.idnet.co.jp/column/page_187.html
# https://qiita.com/ao_log/items/5438f2aaf5c2b46d2ccb